# Generated by Django 4.2.6 on 2023-10-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Indicates whether the user is a teacher.', verbose_name='Teacher status'),
        ),
    ]
