# Generated by Django 4.2.6 on 2023-10-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cgroup_subjects_user_is_teacher_user_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgroup',
            name='group',
            field=models.CharField(help_text='Буква класса (А-Я) на русском языке', max_length=255),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subj',
            field=models.CharField(help_text='Название предмета', max_length=255),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('cgroup', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.cgroup')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
