# Generated by Django 4.2.6 on 2023-10-10 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students', verbose_name='Ученик'),
        ),
    ]
