# Generated by Django 4.2.6 on 2023-10-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_ranks_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgroup',
            name='subjects',
            field=models.ManyToManyField(default=None, to='users.subjects', verbose_name='Предметы у класса'),
        ),
        migrations.AlterField(
            model_name='cgroup',
            name='clas',
            field=models.IntegerField(help_text='Целое число 1-11', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='cgroup',
            name='group',
            field=models.CharField(help_text='Буква класса (А-Я) на русском языке', max_length=255, verbose_name='Литера'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subj',
            field=models.CharField(max_length=255, verbose_name='Название предмета'),
        ),
    ]
