# Generated by Django 4.2.6 on 2023-10-11 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cgroup_subjects_alter_cgroup_clas_alter_cgroup_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranks',
            name='date',
        ),
        migrations.AddField(
            model_name='ranks',
            name='date_mark',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
