# Generated by Django 4.2.6 on 2023-10-11 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_ranks_date_ranks_date_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranks',
            name='date_mark',
        ),
        migrations.AddField(
            model_name='ranks',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
