# Generated by Django 4.2.6 on 2023-10-11 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_ranks_date_mark_ranks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranks',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
