# Generated by Django 4.2.6 on 2023-10-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_ranks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranks',
            name='rank',
            field=models.CharField(choices=[(1, 5), (2, 4), (3, 3), (4, 2), (5, 1), (6, 'Б'), (7, 'Н')], max_length=1, verbose_name='Б/Н/Оценка'),
        ),
    ]
