# Generated by Django 4.2.6 on 2023-10-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_ranks_created_at_alter_ranks_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
