# Generated by Django 4.2.6 on 2023-10-14 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_ranks_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
