# Generated by Django 4.2.6 on 2023-10-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_students_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], default='М', max_length=1),
        ),
    ]
