# Generated by Django 4.2.6 on 2023-10-14 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_students_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranks',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата получения оценки'),
        ),
        migrations.AlterField(
            model_name='students',
            name='cgroup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.cgroup', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=1, verbose_name='Пол'),
        ),
    ]
